def deployToNamespace(namespace, imageName, imageTag) {

    sh """
        echo "========================================"
        echo "Deploying ${imageName}:${imageTag}"
        echo "Namespace : ${namespace}"
        echo "========================================"

        kubectl set image deployment/employee-service \
            employee-service=${imageName}:${imageTag} \
            -n ${namespace}

        echo ""
        echo "Waiting for rollout..."

        kubectl rollout status deployment/employee-service \
            -n ${namespace}

        echo ""
        echo "Current Deployment Image"

        kubectl get deployment employee-service \
            -n ${namespace} \
            -o=jsonpath='{.spec.template.spec.containers[0].image}'

        echo ""
        echo ""
        echo "Pods"

        kubectl get pods -n ${namespace}

        echo ""
        echo ""
        echo "Services"

        kubectl get svc -n ${namespace}
    """
}

pipeline {

    agent any

    environment {

        IMAGE_NAME = "jeshwanth1493/employee-service"
        IMAGE_TAG  = "${BUILD_NUMBER}"

        DEV_NAMESPACE  = "dev"
        QA_NAMESPACE   = "qa"
        PROD_NAMESPACE = "prod"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh '''
                    mvn clean verify
                '''
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        mvn sonar:sonar \
                        -Dsonar.projectKey=Employee-Service
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                 dir('employee-service') {
                            sh """
                                docker build \
                                    -t ${IMAGE_NAME}:${IMAGE_TAG} \
                                    -t ${IMAGE_NAME}:latest .
                            """
                 }
            }
        }

        stage('Docker Push') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                        echo "$DOCKER_PASS" | docker login \
                        -u "$DOCKER_USER" \
                        --password-stdin

                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        docker push ${IMAGE_NAME}:latest

                        docker logout
                    '''
                }
            }
        }

        stage('Deploy to DEV') {
            steps {
                script {
                    deployToNamespace(
                        DEV_NAMESPACE,
                        IMAGE_NAME,
                        IMAGE_TAG
                    )
                }
            }
        }

        stage('Approve QA Deployment') {
            steps {
                input(
                    message: 'Deploy build to QA?',
                    ok: 'Deploy'
                )
            }
        }

        stage('Deploy to QA') {
            steps {
                script {
                    deployToNamespace(
                        QA_NAMESPACE,
                        IMAGE_NAME,
                        IMAGE_TAG
                    )
                }
            }
        }

        stage('Approve PROD Deployment') {
            steps {
                input(
                    message: 'Deploy build to Production?',
                    ok: 'Deploy'
                )
            }
        }

        stage('Deploy to PROD') {
            steps {
                script {
                    deployToNamespace(
                        PROD_NAMESPACE,
                        IMAGE_NAME,
                        IMAGE_TAG
                    )
                }
            }
        }

        stage('Cleanup') {
            steps {

                sh """
                    docker image rm ${IMAGE_NAME}:${IMAGE_TAG} || true
                    docker image rm ${IMAGE_NAME}:latest || true
                """
            }
        }
    }

    post {

        success {
            echo "========================================"
            echo "Pipeline completed successfully!"
            echo "Image: ${IMAGE_NAME}:${IMAGE_TAG}"
            echo "Successfully promoted to Production."
            echo "========================================"
        }

        failure {
            echo "Pipeline failed."
        }

        always {
            cleanWs()
        }
    }
}