apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: employee-service

  template:
    metadata:
      labels:
        app: employee-service

    spec:
      containers:
        - name: employee-service
          image: jeshwanth1493/employee-service:latest

          ports:
            - containerPort: 8080

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: employee-config
                  key: APP_NAME

            - name: APP_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: employee-config
                  key: APP_ENVIRONMENT

            - name: BUILD_NUMBER
              value: "1"